### ISSUE TITLE
c3 compiler for notebooks broken

### ISSUE THREAD

**Issue by romeokienzler** [claimed-framework/c3#16]
`c3_create_operator -r "us.icr.io/geodn" -v 0.0.27 cgw-hls-for-agb-inference.ipynb hls_remove_clouds.ipynb`
results in
```

INFO - Merge first two markdown cells. File name is used as operator name, not first markdown cell.
INFO - Replace shell command with os.system() (        !ipython ./hls_remove_clouds.ipynb satellite={satellite} input_path={input_path} target_path={target_path} log_level={cgw_log_level}
)
Traceback (most recent call last):
  File "/home/romeokienzler/gitco/workflows-and-operators/.venv/bin/c3_create_operator", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/romeokienzler/gitco/workflows-and-operators/.venv/lib64/python3.11/site-packages/c3/create_operator.py", line 242, in main
    create_operator(
  File "/home/romeokienzler/gitco/workflows-and-operators/.venv/lib64/python3.11/site-packages/c3/create_operator.py", line 32, in create_operator
    target_code = convert_notebook(file_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/romeokienzler/gitco/workflows-and-operators/.venv/lib64/python3.11/site-packages/c3/utils.py", line 24, in convert_notebook
    elif cell['cell_type'] == 'code' and cell['source'][0].startswith('%%bash'):
                                         ~~~~~~~~~~~~~~^^^
```

**Comment by blumenstiel** [comment]
fixed in #21
